from dotenv import loadenv
import os

loadenv()

TRAIN_THREAT=os.getenv("TRAIN_THREAT")

TRAIN_KNIFE=os.getenv("TRAIN_KNIFE")
TRAIN_GUN=os.getenv("TRAIN_GUN")
TRAIN_SHURIKEN=os.getenv("TRAIN_SHURIKEN")
TRAIN_SAFE=os.getenv("TRAIN_SAFE")

TRAIN_KNIFE_ANNOTATION=os.getenv("TRAIN_KNIFE_ANNOTATION")
TRAIN_GUN_ANNOTATION=os.getenv("TRAIN_GUN_ANNOTATION")
TRAIN_SHURIKEN_ANNOTATION=os.getenv("TRAIN_SHURIKEN_ANNOTATION")

TEST_KNIFE=os.getenv("TEST_KNIFE")
TEST_GUN=os.getenv("TEST_GUN")
TEST_SHURIKEN=os.getenv("TEST_SHURIKEN")
TEST_SAFE=os.getenv("TEST_SAFE")

TEST_KNIFE_ANNOTATION=os.getenv("TEST_KNIFE_ANNOTATION")
TEST_GUN_ANNOTATION=os.getenv("TEST_GUN_ANNOTATION")
TEST_SHURIKEN_ANNOTATION=os.getenv("TEST_SHURIKEN_ANNOTATION")
